var arrLang = {
  'EN':{
    'titulo':'Telecommunications Technologist',
    'about':' About me',
    'education':' Education',
    'experience':' Experience',
    'proyects': 'Projects',
    'interests': ' Interests',
    'p1_about':'Uruguayan from the departmento of Rocha where I studied Telecommunications Technology at CURE (Centro Universitario Regional del Este).',
    'p2_about':'I am currently working at Prometeo Openbanking, studying in parallel in a self-taught way in the world of development, exploring new challenges and technologies.',
    'h1_experience':'8 Months',
    'h2_experience':'1 Year and 6 Months',
    'h3_experience':'3 Months',
    'h4_experience':'Faro Digital - Intern',
    'h5_experience':'4 Months',
    'p1_experience':'In Prometeo I provided support to clients and the staff of the company either with the integration of the APIs or to help with the correct functioning of different tools.',
    'p2_experience':'I also do operational tasks, improving communication between different areas, generating process documentation and monitoring the correct functioning of the services provided.',
    'p3_experience':'I am a Monitoring Analyst at Prometeo, managing the different monitoring software and creating the corresponding alerts of the services provided by the company.',
    'p4_experience':'I also perform scripts integrated into tools such as Slack, Zabbix, Datadog, Gmail, among others to automate different tasks and optimize response times of the team by obtaining the necessary information quickly.',
    'p5_experience':'In Geocom I was in charge of testing the operation of the SUCIVE website checking each functionality of it and how the data entered was managed.',
    'p5_1_experience':'I also did quality control of a SUCIVE mobile application. Within Geocom I tracked and resolved tickets reported by clients.',
    'p6_experience':'I worked as a team with a Technical Intern of Administration and Accounting, where we carried out an extensive analysis of how the SMEs assigned to us work to advise them and help them improve their business management through the implementation of Software.',
    'p1_education':'The Telecommunications Technologist will have the capabilities to assist in the design and deployment of telecommunications systems, and to perform their maintenance and administration. You will participate as a qualified technician in project development tasks in the area of telecommunications, integrating into the collective and multidisciplinary work',
    'p2_education':'Examination for the Certificate of Competency in English (ECCE), It is a standardized test of English as a foreign language that certifies a high intermediate level.',
    'h1_education': 'Telecommunications Technologist - CURE',
    'h2_education': 'Completed: 2018 - 2021',
    'h3_education': 'Certificate obtained in 2016',
    'h4_education': 'Courses:',
    'read_more': 'Read more >',
    'proyect_h_1':'Objective:',
    'proyect_brou_p_1':'This project focused on the development of a scraping tool to obtain detailed information about bank accounts from BROUs website. The main goal was to facilitate access to personal financial information, allowing the automation of balance inquiries and the execution of transactions.',
    'proyect_h_2':'Tools used:',
    'proyect_brou_p_2':'The project was implemented using the Python programming language, taking advantage of the versatility of the "requests" library. The choice of Python and this specific library allowed to perform HTTP requests efficiently and to manage the responses of the BROU web page in a structured way.',
    'proyect_h_3':'Functionalities Implemented:',
    'proyect_brou_p_3_1':'Access to Banking Information',
    'proyect_brou_p_3_2':'Automation of Transfers',
    'proyect_h_4':'Ethical and Safety Considerations:',
    'proyect_brou_p_4':'It is essential to emphasize that scraping of websites, especially those related to financial information, must be carried out in an ethical manner and respecting the terms of service of the target website. For the reasons described above, the project repository will not be published.',
    'more_information':'More information',
    'close':'Close',
    'more_details': 'Click for more details',
    'proyect_zabbix_p_1':'Project created with the aim of automating the creation of hosts, items and triggers. It allows to adapt to different scenarios through small modifications in the code. The automation of these processes streamlines and simplifies recurring tasks, offering a flexible framework that can be adjusted to meet specific needs.',
    'proyect_zabbix_p_2':'It was developed using Python as the programming language, leveraging the Zabbix API and requests library. Python offers versatility and readability, while the Zabbix API facilitates interaction with the monitoring system. The requests library simplifies HTTP requests, enabling efficient task automation.',
    'proyect_zabbix_p_3_1':'Creation of Hosts, Items and Triggers: Simplify and speed up the configuration of essential elements in Zabbix.',
    'proyect_zabbix_p_3_2':'Adaptability: Allows specific adjustments to suit different contexts and needs.',
    'proyect_h_5':'Repository:',
    'proyect_flask_p_1':'API project in Flask - Python connected to a database. The main focus is to allow users to authenticate and perform custom queries in a simple way. In addition, to simplify both development and deployment of the application, Docker is implemented to manage the service.',
    'proyect_flask_p_2':'This project was created using Python as the main language. Flask was used to develop the API, and the Peewee ORM library was used to manage the interaction with the database. In addition, Docker was implemented to facilitate the management and deployment of the service. Each tool was selected with the goal of building a simple and effective solution.',
    'proyect_flask_p_3_2':'Extract information from a DB.',
    'proyect_flask_p_4':'This repository will not be published because the project was developed collaboratively, respecting the confidential nature of the joint work and protecting the associated intellectual property.',
    'proyect_lineup_p_1':'In this project dedicated to cybersecurity, a beach streaming platform designed for the surf community was evaluated. Using web scraping techniques, we explored the digital infrastructure of the platform to identify potential vulnerabilities.',
    'proyect_lineup_p_2':'Requests: The Requests library was used to make HTTP requests, allowing us to interact with the web infrastructure effectively and retrieve essential data for evaluation.',
    'proyect_lineup_p_3':'cv2 (OpenCV): The cv2 library from OpenCV was incorporated for image processing. This component proved crucial for visually analyzing and manipulating extracted data.',
    'proyect_lineup_p_4':'io, BytesIO, and tempfile: These libraries, specifically io and BytesIO, were essential for working with data in memory and facilitating efficient byte manipulation. tempfile was also implemented to securely manage temporary files during the process.',
    'proyect_lineup_p_5':'It is crucial to emphasize that web scraping, particularly for sites associated with paid services, should be conducted ethically and in compliance with the terms of service of the target website. Due to the aforementioned reasons, the project repository will not be made public.',
    "proyect_easybuyai_p_1": "This project focused on developing a Product Comparison platform using Artificial Intelligence (AI). The main goal was to facilitate decision-making between products when making a purchase, also allowing to obtain the recommended product using the Amazon API.",
    "proyect_easybuyai_p_2": "The project was implemented using the Python programming language, leveraging the versatility of the 'requests' library, the Flask framework to build the backend API, and Bootstrap for the frontend. Additionally, ChatGPT was used for AI recommendations in conjunction with a RapidAPI.com API for Amazon products.",
    "proyect_easybuyai_p_3": "Finally, some controls were also integrated such as Anticaptcha to prevent Bots and CSRFToken to ensure that the tool is consumed from the frontend.",
    "proyect_easybuyai_p_4_1": "Compare among N number of Products",
    "proyect_easybuyai_p_4_2": "Get Amazon Products",
    'proyect_easybuyai_p_4_3':'Get 5 advantages of the recommended product',
    'proyect_easybuyai_p_4_4': 'Get a YouTube review of the recommended product',
    "proyect_easybuyai_p_5": "The Github repository is private since the project is currently functional and under constant development, but I do have an integration repository for platforms.",
    "proyect_discipline_p_1":"Discipline is the gym of a friend that emerged in September 2019, and together with another friend in 2022, we created a clothing brand that represents it. Personally, leveraging my technical expertise, I took on the task of designing a website to showcase our garments and all the work of the coach along with their story.",
    'proyect_discipline_p_2': 'Develop a website that clearly and attractively communicates the essence of the brand, showcasing the products and highlighting their distinctive quality.',
    'proyect_discipline_p_3':"A pre-existing web template based on Bootstrap was chosen to customize and adapt it to Discipline's essence. Bootstrap offered significant benefits, such as an organized structure that simplified customization, adaptability for an optimal experience across different devices, and visual consistency to convey the brand's identity.",
    "footer_p_1": "Here, I have gathered a collection of my projects in the development world.",
    "footer_p_2": "If any of the projects have caught your interest, feel free to get in touch with me.",
    "footer_p_3": "Thank you for visiting my portfolio. See you soon!",
    "footer_titulo_1": "Products",
    "footer_titulo_2": "Useful Links",
    "contact": "Contact",
    'copiar':'Copy',
    'copiar_respuesta':'Copied.'

    
  },  
  'ES':{
    'titulo':'Tecnólogo en Telecomunicaciones',
    'about': ' Sobre mi',
    'education':' Formación',
    'experience':' Experiencia',
    'proyects': 'Proyectos',
    'interests': ' Intereses',
    'p1_about':'Uruguayo del departamento de Rocha donde realicé mis estudios de Tecnólogo en Telecomunicaciones en el CURE (Centro Universitario Regional del Este).',
    'p2_about': 'Actualmente me encuentro trabajando en Prometeo Openbanking, formandome en paralelo de manera autodidacta en el mundo del desarrollo, explorando nuevos desafios y tecnologias. ',
    'h1_experience':'8 Meses',
    'h2_experience':'1 Año y 6 Meses',
    'h3_experience':'3 Meses',
    'h4_experience':'Faro Digital - Pasante',
    'h5_experience':'4 Meses',
    'p1_experience':'En Prometeo brindé soporte tanto a clientes como al personal de la empresa ya sea con la integración de las APIs como ayudar con en el correcto funcionamiento de distintas herramientas.',
    'p2_experience':'Dentro de Prometeo también estoy en la parte operativa, haciendo de nexo entre distintas áreas mejorando la comunicación entre las mismas, generando documentaciones de procesos y monitreo el correcto funcionamiento de los servicios brindados.',
    'p3_experience':'Desempeño el Rol de Monitoring Analyst en Prometeo, gestionando los diferentes softwares de monitoreo y creando las alertas correspondientes de los servicios brindandos por la empresa.',
    'p4_experience':'Ademas realizo Scripts integrados a herramientas como Slack, Zabbix, Datadog, Gmail, entre otras para automatizar diferentes tareas y optimizar los tiempos de respuesta por parte del equipo al obtener la información necesaria de forma rapida.',
    'p5_experience':'En Geocom me encargué de testear el funcionamiento de la página web de SUCIVE chequeando cada funcionalidad de la misma y como se gestionaban los datos ingresados.',
    'p5_1_experience':'También hice control de calidad de una aplicación para movil de SUCIVE. Dentro de Geocom realicé seguimiento y resolución de tickets reportados por clientes.',
    'p6_experience':'En dicho periodo trabajé en equipo con un pasante de la Tecnicatura de Administración y Contabilidad, donde primero debiamos realizar analisis extenso de como trabajan las pymes asignadas a nuestro equipo para asesorarlas y ayudarlas a mejorar su gestión mediante la implementación de Software.',
    'p1_education':'El Tecnólogo en Telecomunicaciones tendrá capacidades para asistir en el diseño y el despliegue de sistemas de telecomunicaciones, y para realizar su mantenimiento y administración. Participará como técnico calificado en tareas de desarrollo de proyectos en el área de las telecomunicaciones, integrándose al trabajo colectivo y multidisciplinario',
    'p2_education': 'Examination for the Certificate of Competency in English (ECCE), es un examen estandarizado de inglés como lengua extranjera que certifica un nivel intermedio alto.',
    'h1_education':'Tecnólogo en Telecomunicaciones - CURE',
    'h2_education': 'Completo: 2018 - 2021',
    'h3_education': 'Certificado obtenido en 2016',
    'h4_education': 'Cursos:',
    'read_more': 'Leer más >',
    'proyect_h_1':'Objetivo:',
    'proyect_brou_p_1':'Este proyecto se enfocó en el desarrollo de un scraping para obtener información detallada de las cuentas bancarias desde la página web del BROU. La meta principal fue facilitar el acceso a la información financiera personal, permitiendo la automatización de consultas de saldos y la ejecución de transacciones.',
    'proyect_h_2':'Herramientas Utilizadas:',
    'proyect_brou_p_2':'El proyecto se implementó utilizando el lenguaje de programación Python, aprovechando la versatilidad de la biblioteca "requests". La elección de Python y esta biblioteca específica permitió realizar solicitudes HTTP de manera eficiente y gestionar las respuestas de la página web del BROU de manera estructurada.',
    'proyect_h_3':'Funcionalidades Implementadas:',
    'proyect_brou_p_3_1':'Acceso a la Información Bancaria',
    'proyect_brou_p_3_2':'Automatización de Transferencias',
    'proyect_h_4':'Consideraciones Éticas y de Seguridad:',
    'proyect_brou_p_4':'Es fundamental destacar que el scraping de sitios web, especialmente aquellos relacionados con información financiera, debe llevarse a cabo de manera ética y respetando los términos de servicio del sitio web objetivo. Por lo anteriormente descripto no se publicará el repositorio del proyecto.',
    'more_information':'Más información',
    'close':'Cerrar',
    'more_details': 'Clickea para más detalles',
    'proyect_zabbix_p_1':'Proyecto realizado con el objetivo de automatizar la creacion de hosts, items y triggers. Permite adaptarse a diversos escenarios mediante pequeñas modificaciones en el código. La automatización de estos procesos agiliza y simplifica tareas recurrentes, ofreciendo un marco flexible que puede ser ajustado para satisfacer las necesidades específicas.',
    'proyect_zabbix_p_2':'Se desarrolló utilizando Python como lenguaje de programación, aprovechando la API de Zabbix y la biblioteca requests. Python ofrece versatilidad y legibilidad, mientras que la API de Zabbix facilita la interacción con el sistema de monitoreo. La biblioteca requests simplifica las solicitudes HTTP, permitiendo la automatización eficiente de tareas.',
    'proyect_zabbix_p_3_1':'Creación de Hosts, Items y Triggers: Simplifica y agiliza la configuración de elementos esenciales en Zabbix.',
    'proyect_zabbix_p_3_2':'Adaptabilidad: Permite ajustes específicos para adecuarse a distintos contextos y necesidades.',
    'proyect_h_5':'Repositorio:',
    'proyect_flask_p_1':'Proyecto API en Flask - Python conectado a una base de datos. El enfoque principal es permitir a los usuarios autenticarse y realizar consultas personalizadas de manera sencilla. Además, para simplificar tanto el desarrollo como el despliegue de la aplicación, se implementa Docker para gestionar el servicio.',
    'proyect_flask_p_2':'Este proyecto se creó utilizando Python como lenguaje principal. Flask se utilizó para desarrollar la API, y la biblioteca Peewee ORM para gestionar la interacción con la base de datos. Además, se implementó Docker para facilitar el manejo y despliegue del servicio. Cada herramienta fue seleccionada con el objetivo de construir una solución simple y efectiva.',
    'proyect_flask_p_3_2':'Extraer información de una DB',
    'proyect_flask_p_4':'Este repositorio no se publicará debido a que el proyecto fue desarrollado de manera colaborativa, respetando la naturaleza confidencial del trabajo conjunto y proteger la propiedad intelectual asociada.',
    'proyect_lineup_p_1':'En este proyecto dedicado a la seguridad informática, se evaluó una plataforma de streaming de playas diseñada para la comunidad de surf. Utilizando técnicas de web scraping, exploramos la infraestructura digital de la plataforma para identificar posibles vulnerabilidades.',
    'proyect_lineup_p_2':'Requests: Se utilizó la librería Requests para realizar solicitudes HTTP, permitiéndonos interactuar con la infraestructura web de manera efectiva y recuperar datos esenciales para la evaluación.',
    'proyect_lineup_p_3':'cv2 (OpenCV): La librería cv2 de OpenCV se incorporó para el procesamiento de imágenes. Este componente resultó crucial para analizar y manipular visualmente datos extraídos.',
    'proyect_lineup_p_4':'io, BytesIO y tempfile: Estas librerías, específicamente io y BytesIO, fueron esenciales para trabajar con datos en memoria y facilitar la manipulación eficiente de bytes. tempfile también se implementó para gestionar archivos temporales de manera segura durante el proceso.',
    'proyect_lineup_p_5':'Es crucial destacar que el web scraping, especialmente en sitios vinculados con servicios pagos, debe llevarse a cabo de manera ética y cumpliendo con los términos de servicio del sitio web objetivo. Debido a las razones mencionadas anteriormente, el repositorio del proyecto no será hecho público.',
    'proyect_easybuyai_p_1':'Este proyecto se enfocó en el desarrollo de una plataforma de comparación de Productos utilizando Inteligencia Artificial (IA). La meta principal fue facilitar la decisión entre productos a la hora de hacer una compra, además permitiendo obtener el producto recomendado utilizando la API de Amazon.',
    'proyect_easybuyai_p_2':'El proyecto se implementó utilizando el lenguaje de programación Python, aprovechando la versatilidad de la biblioteca "requests", el Framework de Flask para construir la API en el backend y bootstrap para el frontend. Además se utilizó ChatGPT para la recomendación de IA en conjunto de una API de RapidAPI.com para los productos de Amazon.',
    'proyect_easybuyai_p_3':'Por último también se integró algunos controles como Anticaptcha para evitar Bots y CSRFToken para que la herramienta sea consumida desde el frontend.',
    'proyect_easybuyai_p_4_1':'Comparar entre N cantidad de Productos',
    'proyect_easybuyai_p_4_2':'Obtener Productos de Amazon',
    'proyect_easybuyai_p_4_3':'Obtener 5 ventajas del producto recomendado',
    'proyect_easybuyai_p_4_4':'Obtener una review de YouTube del producto recomendado',
    'proyect_easybuyai_p_5':'El repositorio de Github es privado ya que el proyecto actualmente esta funcional y en constante desarrollo.',
    "proyect_discipline_p_1":"Discipline es el gimnasio de un amigo que surgé en septiembre de 2019 y juntos en 2022 con otro amigo más, creamos una marca de ropa que lo representa. Personalmente al contar con conocimientos técnicos, me encargué de diseñar un sitio web para mostrar nuestras prendas y todo el trabajo del entrenador junto con su historia.",
    'proyect_discipline_p_2':'Desarrollar una web que comunique de manera clara y atractiva la esencia de la marca, exhibiendo los productos y resaltando su calidad distintiva.',
    'proyect_discipline_p_3':'Se seleccionó una plantilla web preexistente basada en Bootstrap para personalizarla y adaptarla a la esencia de Discipline. Bootstrap ofreció beneficios significativos, como una estructura organizada que simplificó la personalización, adaptabilidad para una experiencia óptima en diferentes dispositivos y consistencia visual para transmitir la identidad de la marca.',
    'footer_p_1':'Aquí, he reunido una colección de mis proyectos en el mundo del desarrollo.',
    'footer_p_2':'Si te ha interesado alguno de los proyectos no dudes en ponerte en contacto conmigo.',
    'footer_p_3':'Gracias por visitar mi portfolio. ¡Hasta pronto!',
    'footer_titulo_1':'Productos',
    'footer_titulo_2':'Links utiles',
    'contact':'Contacto',
    'copiar':'Copiar',
    'copiar_respuesta':'Copiado.'







  }
}


  
$(function () {
  $('.translate').click(function () {
    var lang = $(this).data('lang'); // Recoger el idioma del atributo data-lang

    // Añadir o quitar la clase 'active' para resaltar el idioma seleccionado
    $('.translate').removeClass('active');
    $(this).addClass('active');

    // Iterar sobre elementos con clase 'translate-text' y actualizar su texto
    $('.translate-text').each(function (index, element) {
      var key = $(element).data('key');
      $(element).text(arrLang[lang][key]);
    });
  });
});
